spring.application.name=screen-api

spring.app.jwtSecret=0fcc8a1d465925b3417806a9987494ee8c7fd30e90858c21353c243e50bf259e
spring.app.jwtExpirationMs=3600000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.screen=DEBUG

spring.datasource.url=jdbc:postgresql://3.137.193.199:5432/AuthUsers
spring.datasource.username=postgres
spring.datasource.password=55SWnw78ss8p

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
