name: Deploy Backend and Python API

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_BACKEND_IP }} >> ~/.ssh/known_hosts

    - name: SSH to EC2 and Deploy Code
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACKEND_IP }} << 'EOF'
          set -e

          # Clean up temp dir and re-clone
          rm -rf ~/deploy-temp
          git clone https://${{ secrets.GH_PAT }}github.com/EvilEnforcer/Resume-Screener.git ~/deploy-temp

          # Replace backend (Spring Boot)
          rm -rf ~/myapp/backend
          cp -r ~/deploy-temp/Backend/resume-screener ~/myapp/backend

          # Replace Python API
          rm -rf ~/myapp/pythonapi
          cp -r ~/deploy-temp/Backend/bert-api ~/myapp/pythonapi

          # Clean up temp
          rm -rf ~/deploy-temp

	  cd ~/myapp/backend
	  ./mvnw clean package -DskipTests

          # Rebuild containers
          cd ~/myapp
          docker compose up -d --build
        EOF

